# Generated by Django 5.0.7 on 2024-07-26 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='currency',
            table='currency',
        ),
        migrations.AlterModelTable(
            name='currencyexchange',
            table='currency_exchange',
        ),
    ]
