# Generated by Django 5.0.7 on 2024-07-26 19:14

import common.helpers
import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0002_alter_currency_table_alter_currencyexchange_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('date', models.DateField()),
                ('open_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('high_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('low_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('close_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('adj_close_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('currency_exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencyExch', to='scrapper.currencyexchange')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('currency_exchange', 'date')},
            },
            managers=[
                ('objects', common.helpers.BaseManager()),
            ],
        ),
    ]
