# Generated by Django 5.0.7 on 2024-07-26 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_exchangerates'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exchangerates',
            table='exchange-rates',
        ),
    ]
