# Generated by Django 5.0.7 on 2024-07-26 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0004_alter_exchangerates_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencyexchange',
            unique_together={('from_currency', 'to_currency')},
        ),
    ]
